<a href="https://colab.research.google.com/github/asetya/BigData/blob/master/KNN_explained.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**K-Neirest Neighbour (KNN)**

Algoritma mesin learning golongan lazy learning - dimana algoritma baru akan belajar pada saat harus menyimpulkan kelas atau nilai dari data baru 
sumber : https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_knn_algorithm_finding_nearest_neighbors.htm

Bagian pertama - Import library 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset 

In [2]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'] #berikan header
dataset = pd.read_csv(path, names = headernames) #baca dataset dari file csv 
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

pre-processing data

In [11]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values




array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

tampilkan X

In [12]:
X[1:5,:]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

tampilkan y 

In [13]:
y[1:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

Membagi dataset menjadi 60% data training dan 40% testing 

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

Tampilkan X train dan X test sebelum di standarisasi 

In [18]:
X_train[1:5,:]

array([[6. , 2.2, 5. , 1.5],
       [6.8, 3. , 5.5, 2.1],
       [6.3, 2.3, 4.4, 1.3],
       [5. , 3.6, 1.4, 0.2]])

In [19]:
X_test[1:5,:]

array([[6.7, 3. , 5. , 1.7],
       [6.3, 3.3, 4.7, 1.6],
       [5. , 3.5, 1.3, 0.3],
       [5.7, 4.4, 1.5, 0.4]])

Standarisasi skala 

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

tampilkan X_train
dan X_test yang sudah di standarisasi 

In [21]:
X_train[1:5,:]

array([[ 0.20203198, -1.93993623,  0.69898614,  0.43354648],
       [ 1.20522526, -0.01867889,  0.99158498,  1.2666963 ],
       [ 0.57822946, -1.69977906,  0.34786752,  0.15582987],
       [-1.05195962,  1.42226411, -1.40772557, -1.37161146]])

In [22]:
X_test[1:5,:]

array([[ 1.0798261 , -0.01867889,  0.69898614,  0.71126309],
       [ 0.57822946,  0.70179261,  0.52342683,  0.57240478],
       [-1.05195962,  1.18210695, -1.46624534, -1.23275316],
       [-0.1741655 ,  3.34352146, -1.3492058 , -1.09389486]])

**Start KNN disini **

Misal dipilih k = 3

In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

gunakan model yang sudah dibuat untuk memprediksi nilai perkiraan y - dari data testing 


In [25]:
y_pred = classifier.predict(X_test)

Melihat hasil dan menampilkan evaluasi untuk ukuran baik buruknya hasil klasifikasi menggunakan confussion matrix dan akurasi 


In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[22  0  0]
 [ 0 15  2]
 [ 0  1 20]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       0.94      0.88      0.91        17
 Iris-virginica       0.91      0.95      0.93        21

       accuracy                           0.95        60
      macro avg       0.95      0.94      0.95        60
   weighted avg       0.95      0.95      0.95        60

Accuracy: 0.95
