<a href="https://colab.research.google.com/github/asetya/BigData/blob/master/KNNRegresi_explained.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**KNN untuk permasalahan Regresi**

sumber : https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_knn_algorithm_finding_nearest_neighbors.htm



import library

In [2]:
import numpy as np
import pandas as pd

Dowload dataset 



In [42]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/slump/slump_test.data"
headernames = ['id', 'label', 'time', 'petal-width', 'Class']
data = pd.read_csv(url)
array = data.values
X = array[:,1:10]
Y = array[:,10]
data.shape


(103, 11)

tamplikan data, X dan y 

In [40]:
data.head(3)

No  Cement   Slag  ...  SLUMP(cm)  FLOW(cm)  Compressive Strength (28-day)(Mpa)
0   1   273.0   82.0  ...       23.0      62.0                               34.99
1   2   163.0  149.0  ...        0.0      20.0                               41.14
2   3   162.0  148.0  ...        1.0      20.0                               41.81

[3 rows x 11 columns]

In [43]:
X[0:9,:]

array([[273. ,  82. , 105. , 210. ,   9. , 904. , 680. ,  23. ,  62. ],
       [163. , 149. , 191. , 180. ,  12. , 843. , 746. ,   0. ,  20. ],
       [162. , 148. , 191. , 179. ,  16. , 840. , 743. ,   1. ,  20. ],
       [162. , 148. , 190. , 179. ,  19. , 838. , 741. ,   3. ,  21.5],
       [154. , 112. , 144. , 220. ,  10. , 923. , 658. ,  20. ,  64. ],
       [147. ,  89. , 115. , 202. ,   9. , 860. , 829. ,  23. ,  55. ],
       [152. , 139. , 178. , 168. ,  18. , 944. , 695. ,   0. ,  20. ],
       [145. ,   0. , 227. , 240. ,   6. , 750. , 853. ,  14.5,  58.5],
       [152. ,   0. , 237. , 204. ,   6. , 785. , 892. ,  15.5,  51. ]])

In [44]:
Y[0:3]

array([34.99, 41.14, 41.81])

  Bagi data menjadi 60 % training dan 40% testing 
  

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.40)

Misalkan y = yang harus diperkirakan adalah "Compressive Strength (28-day)(Mpa)" 

masukan X ADALAH KOLOM : Cement,Slag,Fly ash,Water,SP,Coarse Aggr.,Fine Aggr.,SLUMP(cm),FLOW(cm)

Kita akan menggunakan KNN untuk melakukan regresi dengan mengimport library KNN regresi sebagai berikut 


In [46]:
from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 10)
knnr.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                    weights='uniform')

Menampilkan error y hasil prediksi 

dan y test 

In [54]:
y_predict = knnr.predict(X_test)
y_predict



array([43.52 , 39.223, 40.684, 31.384, 34.448, 41.74 , 38.367, 30.701,
       33.296, 44.845, 31.919, 37.686, 34.675, 40.642, 35.426, 43.548,
       33.03 , 30.018, 43.52 , 44.711, 37.67 , 41.004, 33.432, 32.146,
       33.432, 36.483, 36.669, 37.058, 32.12 , 35.933, 30.715, 37.67 ,
       34.729, 37.67 , 34.729, 44.364, 29.363, 34.769, 35.72 , 31.746,
       36.053, 39.156])

In [55]:
y_test

array([49.3 , 37.39, 38.46, 31.77, 33.91, 42.08, 34.18, 18.26, 36.46,
       38.59, 26.82, 33.11, 33.38, 39.4 , 31.37, 43.95, 31.5 , 19.19,
       52.65, 45.42, 41.81, 46.36, 41.81, 27.62, 41.14, 36.19, 34.99,
       28.03, 37.66, 35.52, 30.43, 41.01, 36.72, 41.54, 28.7 , 44.08,
       17.19, 25.21, 32.71, 26.28, 32.44, 49.97])

Menampilkan Mean square Error 

In [56]:
print ("The MSE is:",format(np.power(y_test-y_predict,2).mean()))

The MSE is: 31.433718666666657
